services:

  api:
    build:
      context: .
    ports:
      - 5000:5000
    container_name: rest_flask_api
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.4-rc0-noble
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
